In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

add_arr = arr + 2
print("After adding 2:", add_arr)

mul_arr = arr * 3
print("After multiplying by 3:", mul_arr)

div_arr = arr / 2
print("After dividing by 2:", div_arr)


After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
arr_reverse = np.array([1, 2, 3, 6, 4, 5])[::-1]
print("Reversed array:", arr_reverse)

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

# i. For array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
value_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {value_x}, Indices: {indices_x}")

# ii. For array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
value_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {value_y}, Indices: {indices_y}")


Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

a = arr[0, 1]
print("Element at 1st row, 2nd column:",a)

b = arr[2, 0]
print("Element at 3rd row, 1st column:",b)

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [4]:
Anshuman = np.linspace(10, 100, 25)
print(Anshuman)

print("Dimensions:", Anshuman.ndim)
print("Shape:", Anshuman.shape)
print("Total elements:", Anshuman.size)
print("Data type:", Anshuman.dtype)
print("Total bytes consumed:", Anshuman.nbytes)

transpose = Anshuman.reshape(25, 1)
print("\nTranspose:\n", transpose)

print("\nUsing T attribute:\n", Anshuman.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transpose:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
ucs420_Anshuman = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_Anshuman))
print("Median:", np.median(ucs420_Anshuman))
print("Max:", np.max(ucs420_Anshuman))
print("Min:", np.min(ucs420_Anshuman))
print("Unique elements:", np.unique(ucs420_Anshuman))

reshaped = ucs420_Anshuman.reshape(4, 3)
print("\nReshaped:\n", reshaped)

resized = np.resize(ucs420_Anshuman, (2, 3))
print("\nResized:\n", resized)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized:
 [[10 20 30]
 [40 50 60]]
